### ISSUE TITLE
Missing context (then set), makes create fail. 

### ISSUE THREAD

**Issue by niedbalski** [calyptia/cli#449] opened 2023-06-13 15:40 UTC
# Bug Report

Missed context 

```
➜ core-operator (main) ✔ calyptia create core_instance operator test
Error: could not ensure kubernetes namespace exists: exists: resource name may not be empty

➜ core-operator (main) ✔ kubectl config set-context --current --namespace=test
Context "kind-kind" modified.


➜ core-operator (main) ✔ calyptia create core_instance operator test
Error: could not ensure kubernetes namespace exists: exists: resource name may not be empty
```

**Comment by gabrielbussolo** [comment] 2023-07-13 07:18
i couldn't reproduce this issue anymore, I guess it stopped happening when we did:
https://github.com/calyptia/cli/blob/d611fb385a793404f5559fa42277f85269fea906/cmd/coreinstance/create_core_instance_operator.go#L49-L64

so im closing the issue

**Closed by gabrielbussolo** 2023-07-13 07:18 UTC
